// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * SearchResult represents a search match
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("groupKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupKey"] = "";
        }
        if (!("groupName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupName"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {models$0.Command}
             */
            this["command"] = (new models$0.Command());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField2_0($$parsedSource["command"]);
        }
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = models$0.Command.createFrom;
