// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Command represents a single stored command
 */
export class Command {
    /**
     * Creates a new Command instance.
     * @param {Partial<Command>} [$$source = {}] - The source object to create the Command.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("cmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cmd"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Command instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Command}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new Command(/** @type {Partial<Command>} */($$parsedSource));
    }
}

/**
 * CommandsFile is the root structure of commands.json
 */
export class CommandsFile {
    /**
     * Creates a new CommandsFile instance.
     * @param {Partial<CommandsFile>} [$$source = {}] - The source object to create the CommandsFile.
     */
    constructor($$source = {}) {
        if (!("_meta" in $$source)) {
            /**
             * @member
             * @type {Meta}
             */
            this["_meta"] = (new Meta());
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: Group }}
             */
            this["groups"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandsFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandsFile}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("_meta" in $$parsedSource) {
            $$parsedSource["_meta"] = $$createField0_0($$parsedSource["_meta"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField1_0($$parsedSource["groups"]);
        }
        return new CommandsFile(/** @type {Partial<CommandsFile>} */($$parsedSource));
    }
}

/**
 * Config represents the app configuration
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("data_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * Group represents a collection of related commands
 */
export class Group {
    /**
     * Creates a new Group instance.
     * @param {Partial<Group>} [$$source = {}] - The source object to create the Group.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("commands" in $$source)) {
            /**
             * @member
             * @type {Command[]}
             */
            this["commands"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Group}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        return new Group(/** @type {Partial<Group>} */($$parsedSource));
    }
}

/**
 * Meta contains file metadata
 */
export class Meta {
    /**
     * Creates a new Meta instance.
     * @param {Partial<Meta>} [$$source = {}] - The source object to create the Meta.
     */
    constructor($$source = {}) {
        if (!("purpose" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["purpose"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Meta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Meta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Meta(/** @type {Partial<Meta>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Meta.createFrom;
const $$createType2 = Group.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = Command.createFrom;
const $$createType5 = $Create.Array($$createType4);
